### ISSUE TITLE
Merge beta to main using fast forward

### ISSUE THREAD

**Issue by AllanOricil** [mcarvin8/sfdx-decomposer-plugin#19]
I think that this way release notes and changelog will be right. Right? Not sure haha

Because then all commits from beta will be included in main. Then you can recreate beta from main head.

**Comment by mcarvin8** [comment]
Hahaha I'll try this next release, thanks for the tip @AllanOricil !

**Comment by AllanOricil** [comment]
@mcarvin8 [Github uses by default --no-ff](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github). Because we want all commits to be added again to main we have to use ff. You could use rebase and merge next time, I think. Sorry for the confusion haha

**Comment by AllanOricil** [comment]
Actually I don't know, really. Semantic-release's [doc](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/release-workflow/pre-releases.md) says to do a --no-ff  :(

**Comment by AllanOricil** [comment]
I asked semantic-release devs how to do it
https://github.com/semantic-release/semantic-release/discussions/3170

**Comment by AllanOricil** [comment]
nooooo, sorry. Release notes are right. I don't know why I saw they were wrong. My bad. Merge with --no-ff works.

**Comment by mcarvin8** [comment]
Thanks @AllanOricil , yea I think I have the jest now of formatting the commit messages to trigger a release, so I'll make sure to get in that habit when pushing new stuff.
